---
- hosts: vm
  user: dkostmii
  become: true
  become_method: sudo
  tasks:
    - name: Install package (Debian)
      when: ansible_os_family == "Debian"
      ansible.builtin.apt:
        name: "{{ package_name }}"

    - name: Install package (RedHat)
      when: ansible_os_family == "RedHat"
      ansible.builtin.yum:
        name: "{{ package_name }}"
